#Travis-Ci
dist: trusty
sudo: required
language: python

python:
- 3.5
- 3.6

branches:
  only:
    - master
    - /^dev\d*[.]?\d*$/

before_install:
  #SWIG
  - sudo apt -y install swig

script:
  - sudo apt-get -y install desktop-file-utils
  - make

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
