dist: trusty
sudo: required
language: python

python:
- 3.4
- 3.5

before_install:
  #SIP
  - cd ..
  - curl -L -O "https://sourceforge.net/projects/pyqt/files/sip/sip-4.19.3/sip-4.19.3.tar.gz"
  - tar -xvf sip-4.19.3.tar.gz
  - cd sip-4.19.3
  - python configure.py
  - sudo make install
  #PyQt5
  - cd ..
  - curl -L -O "https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.9/PyQt5_gpl-5.9.tar.gz"
  - tar -xvf PyQt5_gpl-5.9.tar.gz
  - cd PyQt5_gpl-5.9
  - python configure.py --confirm-license
  - sudo make install
  - cd $TRAVIS_BUILD_DIR

install:
  - pip install -r requirements.txt
  - pip install pyinstaller

script:
 - make

before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
