# Travis-CI for Pyslvs-UI
language: python
os: linux
dist: xenial

jobs:
  include:
    - &linux
      python: "3.7"
      before_install:
        - python3 -m pip install pip setuptools -U
        - python3 -m pip install -e . -U

    - <<: *linux
      python: "3.8"

    - <<: *linux
      python: "3.9"

script:
  - make pack

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
