# Travis-CI for Pyslvs-UI
language: python
os: linux
dist: xenial

jobs:
  include:
    - &linux
      python: "3.7"
      before_install:
        - python3 -m pip install pip -U
        - python3 -m pip install -r requirements.txt -U
        - python3 -m pip install -r pyslvs/requirements.txt -U
      install:
        - make test-pack
        - python3 setup.py install

    - <<: *linux
      python: "3.8"
      addons:
        apt:
          update: true
          packages:
            - libhdf5-dev

    - &win
      os: windows
      # 'generic' will cause infinity loop
      language: shell
      env:
        - PYTHON=3.7.7
        - PY=37
        - COMPILER=mingw32
      before_install:
        # Install Python
        - choco install -y python --version ${PYTHON}
        - export PYDIR=/c/Python${PY}
        - export PATH=${PYDIR}:${PYDIR}/Scripts:${PATH}
        - sh ./pyslvs/platform/set_pycompiler.sh ${PYDIR} ${COMPILER}
        - cp ${PYDIR}/python.exe ${PYDIR}/python3.exe
        - python3 -m pip install pip setuptools -U
        - python3 --version
        - python3 -m pip --version
        - python3 -m pip install -r requirements.txt -U
        - python3 -m pip install -r pyslvs/requirements.txt -U
        # Select Msys2
        - export PATH=/c/tools/msys64/mingw64/bin:${PATH}
      install:
        - mingw32-make test-pack
      before_cache:
        - ${msys2} pacman --sync --clean --noconfirm
      cache:
        directories:
          - ${HOME}/AppData/Local/Temp/chocolatey
          - /c/tools/msys64

    - <<: *win
      env:
        - PYTHON=3.8.5
        - PY=38
        - COMPILER=mingw32

    - <<: *win
      env:
        - PYTHON=3.7.0
        - PY=37
        - COMPILER=msvc

    - <<: *win
      env:
        - PYTHON=3.8.5
        - PY=38
        - COMPILER=msvc

    - &osx
      os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=3.7.0
      before_install:
        - brew update
        # Install pyenv
        - brew upgrade pyenv || true
        - ln -s /usr/local/bin/greadlink /usr/local/bin/readlink
        - export PATH=/Users/travis/.pyenv/shims:${PATH}
        # Install Python
        - env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install ${PYTHON}
        - pyenv global ${PYTHON}
        - python3 -m pip install pip -U
        - pyenv rehash
        - python3 --version
        - python3 -m pip --version
        - python3 -m pip install -r requirements.txt -U
        - python3 -m pip install -r pyslvs/requirements.txt -U
      install:
        - make test-pack

    - <<: *osx
      env: PYTHON=3.8.5

script:
  - python3 setup.py test

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
