# Travis-Ci for Pyslvs
language: python

matrix:
  include:
    
    - os: linux
      sudo: required
      python: 3.6
      dist: xenial
    
    - os: linux
      sudo: required
      python: 3.7
      dist: xenial
    
    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=3.6.6

branches:
  only:
    - master
    - /^dev\d*[.]?\d*$/

addons:
  apt:
    packages:
      - swig

# For OSX
before_install: |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
  brew install swig;
  brew outdated pyenv || brew upgrade pyenv;
  brew install pyenv-virtualenv;
  pyenv install $PYTHON;
  export PYENV_VERSION=$PYTHON;
  export PATH="/Users/travis/.pyenv/shims:${PATH}";
  pyenv-virtualenv venv;
  source venv/bin/activate;
  python --version;
  pip install -r requirements.txt;
  pip install pyinstaller;
  fi

script:
  - make

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
