# Travis-Ci for Pyslvs
language: python

matrix:
  include:
    
    - os: linux
      sudo: required
      python: 3.6
      dist: xenial
    
    - os: linux
      sudo: required
      python: 3.7
      dist: xenial
    
    - os: osx
      osx_image: xcode10
      python: 3.6

branches:
  only:
    - master
    - /^dev\d*[.]?\d*$/

addons:
  apt:
    packages:
      - swig

before_install:
  # For OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig; fi

script:
  - make

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
