# Travis-CI for Pyslvs-UI
language: python
os: linux
dist: xenial

git:
  depth: 1

jobs:
  include:
    - &linux
      python: "3.7"
      before_install:
        - python3 -m pip install pip -U
        - python3 -m pip install -r requirements.txt -U
      install:
        - make pack
        - python3 setup.py install

    - <<: *linux
      python: "3.8"
      addons:
        apt:
          update: true
          packages:
            - libhdf5-dev
      after_success:
        # PyPI deployment
        - if [[ "$TRAVIS_REPO_SLUG" == "KmolYuan/Pyslvs-UI" && -n "$TRAVIS_TAG" ]]; then
          python3 -m pip install twine;
          python3 setup.py bdist_wheel;
          python3 -m twine upload dist/*.whl --skip-existing;
          fi
      deploy:
        - &generic-deploy
          provider: releases
          overwrite: true
          token: $TRAVIS_TOKEN
          file_glob: true
          file: out/*.AppImage
          cleanup: false
          on:
            tags: true

    - &win
      os: windows
      # 'generic' will cause infinity loop
      language: bash
      env:
        - PYTHON=3.7.0
        - PYTHON_DIR=/C/Python37
        - COMPILER=mingw32
      before_install:
        - git submodule update --init --recursive
        # Install Msys2
        - |-
          case ${TRAVIS_OS_NAME} in
            windows)
              [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
              choco uninstall -y mingw
              choco upgrade --no-progress -y msys2
              export msys2='cmd //C RefreshEnv.cmd '
              export msys2+='& set MSYS=winsymlinks:nativestrict '
              export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
              export mingw64="${msys2} -mingw64 -full-path -here -c "\"\$@"\" --"
              export msys2+=" -msys2 -c "\"\$@"\" --"
              ${msys2} pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
              taskkill //IM gpg-agent.exe //F
              export PATH=/C/tools/msys64/mingw64/bin:${PATH}
              export MAKE=mingw32-make
              ;;
          esac
        # Install Python
        - choco install -y python --version ${PYTHON}
        - export PATH=${PYTHON_DIR}:${PYTHON_DIR}/Scripts:${Path}
        - cmd.exe pyslvs/platform/set_pycompiler.bat ${PYTHON_DIR} ${COMPILER}
        - python -m pip install pip setuptools -U
        - python --version
        - python -m pip --version
        - python -m pip install -r requirements.txt -U
        - gcc --version
        - mingw32-make --version
      install:
        - mingw32-make test-pack
        - python setup.py install
      before_cache:
        - |-
          case $TRAVIS_OS_NAME in
            windows)
              $msys2 pacman --sync --clean --noconfirm
              ;;
          esac
      cache:
        directories:
          - ${HOME}/AppData/Local/Temp/chocolatey
          - /C/tools/msys64

    - <<: *win
      env:
        - PYTHON=3.8.0
        - PYTHON_DIR=/C/Python38
        - COMPILER=mingw32

    - <<: *win
      env:
        - PYTHON=3.7.0
        - PYTHON_DIR=/C/Python37
        - COMPILER=msvc

    - <<: *win
      env:
        - PYTHON=3.8.0
        - PYTHON_DIR=/C/Python38
        - COMPILER=msvc

    - &osx
      os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=3.7.0
      before_install:
        - git submodule update --init --recursive
        - brew update
        # Install pyenv
        - brew upgrade pyenv || true
        - ln -s /usr/local/bin/greadlink /usr/local/bin/readlink
        - export PATH=/Users/travis/.pyenv/shims:${PATH}
        # Install Python
        - env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install ${PYTHON}
        - pyenv global ${PYTHON}
        - python3 -m pip install pip -U
        - pyenv rehash
        - python3 --version
        - python3 -m pip --version
        - python3 -m pip install -r requirements.txt -U
      install:
        - make test-pack
        - python3 setup.py install
        - pyenv rehash

    - <<: *osx
      env: PYTHON=3.8.0
      deploy:
        - <<: *generic-deploy
          file: dist/*.zip

script:
  - pyslvs test

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
