# Travis-CI for Pyslvs-UI
language: python
os: linux
dist: xenial

jobs:
  include:
    - &linux
      python: "3.7"
      before_install:
        - python3 -m pip install pip -U
        - python3 -m pip install -r requirements.txt -U
        - python3 -m pip install -r pyslvs/requirements.txt -U
      install:
        - make test-pack
        - python3 setup.py install

    - <<: *linux
      python: "3.8"

    - <<: *linux
      python: "3.9"

script:
  - make test

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
