# AppVeyor for Pyslvs-UI
image: Visual Studio 2017

platform:
  - x64

environment:
  matrix:

    - MINGW_DIR: &mingw C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0
      MSYS_DIR: &msys2 C:\msys64
      PYTHON_DIR: C:\Python37-x64

install:
  # Environment variables
  - set Path=%MINGW_DIR%\mingw64\bin;%MSYS_DIR%\usr\bin;%Path%
  - set Path=%PYTHON_DIR%;%PYTHON_DIR%\Scripts;%Path%

  # Show Python
  - python --version
  - pip --version

  # Upgrade setuptools
  - pip install setuptools -U

  # Set Python compiler to MinGW
  - platform\set_pycompiler %PYTHON_DIR%

  # Install modules
  - pip install -r requirements.txt
  - pip install pyinstaller

  # Show tool kits
  - pyinstaller --version
  - gcc --version
  - mingw32-make --version

before_build:
  # Clone submodules
  - git submodule update --init
  - git submodule update --init --recursive depend/pyslvs

build_script:
  - mingw32-make

artifacts:
  - path: dist/pyslvs-*.exe
    name: pyslvs

deploy:
  - release: Pyslvs $(APPVEYOR_REPO_TAG_NAME)
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: ""
    provider: GitHub
    auth_token: $(APPVEYOR_TOKEN)
    artifacts: pyslvs
    force_update: true
    on:
      appveyor_repo_tag: true
      PYTHON_DIR: C:\Python37-x64
