# AppVeyor for Pyslvs-PyQt5
image: Visual Studio 2017

platform:
- x64

environment:
  matrix:

  - MINGW_DIR: &mingw C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
    MSYS_DIR: &msys2 C:\msys64\usr\bin
    PYTHON_DIR: C:\Python36-x64

  - MINGW_DIR: *mingw
    MSYS_DIR: *msys2
    PYTHON_DIR: C:\Python37-x64

cache:
# swig.exe
- C:\ProgramData\chocolatey\bin -> appveyor.yml
# supporting swig Lib files.
- C:\ProgramData\chocolatey\lib -> appveyor.yml

install:
# Install SWIG.
- choco install swig --yes --limit-output

# Environment variables.
- set Path=%PYTHON_DIR%;%Path%
- set Path=%PYTHON_DIR%\Scripts;%Path%
- set Path=%MSYS_DIR%;%Path%
- set Path=%MINGW_DIR%;%Path%

# Show Python.
- python --version
- pip --version

# Set Python compiler to Msys2.
- pip install setuptools -U
- echo [build]>> %PYTHON_DIR%\Lib\distutils\distutils.cfg
- echo compiler = mingw32>> %PYTHON_DIR%\Lib\distutils\distutils.cfg
- patch %PYTHON_DIR%\lib\distutils\cygwinccompiler.py platform\patch.diff
- copy %PYTHON_DIR%\vcruntime140.dll %PYTHON_DIR%\libs

# Install modules.
- pip install -r requirements.txt
- pip install pyinstaller

# Show tool kits.
- pyinstaller --version
- gcc --version
- mingw32-make --version
- swig -version

before_build:
# Clone submodules.
- git submodule update --init --recursive

build_script:
- mingw32-make

test: off

artifacts:
- path: dist/pyslvs-*.exe
  name: pyslvs

deploy:
- release: Pyslvs $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: ""
  provider: GitHub
  auth_token: $(APPVEYOR_TOKEN)
  artifacts: pyslvs
  force_update: true
  on:
    appveyor_repo_tag: true
    PYTHON_DIR: C:\Python37-x64
