site_name: Pyslvs
theme: readthedocs
pages:
  - Getting Start:
    - Introduction: index.md
    - Environment: environment.md
  - About:
    - License: license.md
    - Releated Modules: releated.md
    - Change Log: changelog.md
