site_name: Pyslvs
theme: readthedocs
repo_url: https://github.com/KmolYuan/Pyslvs-UI
copyright: Copyright © 2016-2019 Yuan Chang
site_favicon: favicon.ico

markdown_extensions:
    - toc:
        permalink: True
    - admonition

nav:
    - Home: index.md
    - Getting Start:
        - Introduction: introduction.md
        - Environment: environment.md
    - User Interface:
        - Mechanism: mechanism.md
        - Inputs: inputs.md
        - Synthesis: synthesis.md
        - Version Control: version-control.md
        - Settings: settings.md
    - About:
        - License: license.md
        - Releated Modules: releated.md
        - Change Log: changelog.md
