site_name: Pyslvs
theme: readthedocs
repo_url: https://github.com/KmolYuan/Pyslvs-UI
copyright: Copyright © 2016-2019 Yuan Chang
site_favicon: favicon.ico
site_description: The manual of Pyslvs, Open Source Planar Linkage Mechanism Simulation and Mechanical Synthesis System.

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - smarty
    - attr_list

nav:
    - Home: index.md
    - Getting Start:
        - Introduction: introduction.md
        - Environment: environment.md
    - User Interface:
        - Mechanism: mechanism.md
        - Inputs: inputs.md
        - Synthesis: synthesis.md
        - IO: io.md
        - Settings: settings.md
    - Libraries:
        - Pyslvs Libraries: pyslvs-lib.md
        - Python-Solvespace Library: python-solvespace-lib.md
        - Python-Solvespace API: python-solvespace-api.md
    - About:
        - References: license.md
        - Releated Modules: releated.md
        - Change Log: changelog.md
