name: Python type check
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download submodules
        run: git submodule update --init --recursive
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install pip mypy -U
          pip install -e . -U
          pip install -e pyslvs -U
      - name: Lint with mypy
        run: mypy -m launch_pyslvs
